### ISSUE TITLE
Some questions, please

### ISSUE THREAD

**Issue by JohnRConrad** [Mob-Barley/noise_level_protocol#1]
Dear Mob-Barley,

Your post gives me hope that I may be able to use it to solve a long-standing dispute with my neighbor who is robbing me of sleep many nights, but refuses to own the problem.  I would be very grateful to you if we could communicate a bit so that I can learn from you.  Could you please send me an email at john.conrad@furman.edu.

I am on the physics dept. faculty at Furman University:
http://www2.furman.edu/academics/physics/meet-our-faculty/Pages/John-R-Conrad.aspx

Thanks, 

John

**Comment by Mob-Barley** [comment]
Dear John,

thank you for the interest in my project. Please excuse the late answer, but I forgot to set notifications on github.
Unfortunately, I don't have enough time to provide you a more detailed tutorial.
I dont know your background, but some basic knowledge in linux/raspbian and programming is preferable for this project, because it has no real userinterface and runs in the terminal.
I would invite you to start recreating this project with the information from the readme and come back, if you have a specific question.

Best regards,

Mob
